Initial Army branch card
jpadwor1/should-i-serve pull request #34
Opened 2024-07-24 19:04 UTC by S10SEN

Created Army Branch card component. 

Has Army image and working links.

Links were put in constants.ts then imported into component.

2024-07-24 19:23 UTC, jpadwor1 commented on src/lib/constants.ts
> +   export const armyLinks =
Lets use a data structure like this
export const branches = [
  {
    name: "Army",
    logo: "/usarmy.jpg",
    links: {
      main: "https://www.goarmy.com/",
      reserve: "https://www.usar.army.mil/",
      nationalGuard: "https://www.nationalguard.com/"
    }
  },
  {
    name: "Navy",
    logo: "/usnavy.jpg",
    links: {
      main: "https://www.navy.com/",
      reserve: "https://www.navyreserve.navy.mil/",
      nationalGuard: ""
    }
  },
//add remaining branch details
]

2024-07-24 19:25 UTC, jpadwor1 commented on src/app/page.tsx
> +        <BranchCard />
Great job, in the issue I mentioned having the ability to pass the image source as a prop and other branch specific info. If we do this we can have one <BranchCard/> and use if for Army, Navy, AF, etc. In the current configuration we have to make other cards specific to the branches.

We should map over the branches from constants.ts and render a BranchCard for each like this:

<BranchCard branch={branch}/>

2024-07-24 19:31 UTC, jpadwor1 requested changes
Great Job

2024-07-24 19:31 UTC, jpadwor1 commented on src/components/ui/branch-card.tsx
> +const BranchCard = () => {
Add the branch props. They should match the type of the branches from constants.ts

interface BranchCardProps {
name: string;
logo: string;
links: {
main: string;
//etc.
}

2024-07-24 19:31 UTC, jpadwor1 commented on src/components/ui/branch-card.tsx
> +                src="/usarmy.jpg"
Use dynamic variable for image source.

Should be 
src={branch.logo}

2024-07-24 19:31 UTC, jpadwor1 commented on src/components/ui/branch-card.tsx
> +                Army National Guard
should be dynamic

2024-07-24 19:31 UTC, jpadwor1 commented on src/components/ui/branch-card.tsx
> +            <a href={armyLinks.army}>
In NextJS, try not to use <a> tags. Instead use <Link>. Import it from 'next/link' like this

import Link from 'next/link'

2024-07-24 23:28 UTC, jpadwor1 commented on src/components/ui/branch-card.tsx
> + interface BranchCardProps {
import Image from "next/image";
import Link from "next/link";
import React from "react";

interface BranchCardProps {
  branch: {
    name: string;
    logo: string;
    links: {
      name: string;
      url: string;
    }[];
  };
}
const BranchCard = ({ branch }: BranchCardProps) => {
  return (
    <div className="justify center flex flex-col items-center bg-white text-black">
      <div>
        <Image
          className=""
          src={branch.logo}
          alt="Logo"
          width={100}
          height={100}
        />
      </div>
      <div>
        {branch.links.map((link) => (
          <Link href={link.url}>{link.name}</Link>
        ))}
      </div>
    </div>
  );
};

export default BranchCard;

2024-07-24 23:30 UTC, jpadwor1 commented on src/lib/constants.ts
> +   export const branches = [
If we put the links in an array we can map over them. We also won't need to hardcode National or Reserve into the component. 
```
export const branches = [
    {
      name: "Army",
      logo: "/usarmy.jpg",
      links: [
        { name: "Main", url: "https://www.goarmy.com/" },
        { name: "Reserve", url: "https://www.usar.army.mil/" },
        { name: "National Guard", url: "https://www.nationalguard.com/" }
      ]
    },
    {
      name: "Navy",
      logo: "/usnavy.jpg",
      links: [
        { name: "Main", url: "https://www.navy.com/" },
        { name: "Reserve", url: "https://www.navyreserve.navy.mil/" }
      ]
    },
  ]

2024-07-24 23:37 UTC, jpadwor1 commented on src/app/page.tsx
> +        <div className="flex flex-row items-center gap-2">
Make sure to call the component like this

to display multiple cards map over branches
  ```
  {branches.map((branch) => (
  <BranchCard branch={branch} />
  ))}
```

For just one card we have to specify which branch we want by index or find it another way.

```
<BranchCard branch={branches[0]} />
```

2024-07-24 23:40 UTC, jpadwor1 requested changes
I left some comments.

Change branches.links to an array of objects

Update interface BranchCardProps to accompany the new array

map over branch.links to display each Link

2024-07-25 00:31 UTC, S10SEN commented
I think I got it this time, could use some adjustment with the images I think.

2024-07-25 19:22 UTC, jpadwor1 approved these changes

2024-07-25 19:22 UTC, merged